defaults: &defaults
  adapter: postgresql
  database: chelitas
  username: chelitas
  password:

production:
  <<: *defaults
  database: chelitas_production

staging:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults
  database: chelitas_test
